import React from 'react';
import Header from '../components/Header';
import { Shield, Zap, BarChart2, Globe, Code, RefreshCw } from 'lucide-react';

export default function Features({ username, onLogout, onOpenAuth, onOpenInfo }) {
  const featureList = [
    {
      icon: <Zap className="h-6 w-6 text-blue-600 dark:text-blue-400" />,
      title: "Instant Redirections",
      description: "Redirection requests are resolved in milliseconds via a high-performance Redis cache layer, reducing user wait times to zero."
    },
    {
      icon: <BarChart2 className="h-6 w-6 text-purple-600 dark:text-purple-400" />,
      title: "Real-time Metrics",
      description: "Monitor click rates, geo-location statistics, device distributions, and referral links as they happen."
    },
    {
      icon: <Shield className="h-6 w-6 text-green-600 dark:text-green-400" />,
      title: "Secure SSL Links",
      description: "Every link generated by ShortUrl comes with custom SSL encryption by default, safeguarding your users from phishing warnings."
    },
    {
      icon: <Globe className="h-6 w-6 text-orange-600 dark:text-orange-400" />,
      title: "Custom Domains",
      description: "Build trust and increase click-through rates by shortening links using your own brand's custom domain name."
    },
    {
      icon: <Code className="h-6 w-6 text-indigo-600 dark:text-indigo-400" />,
      title: "Developer REST API",
      description: "Integrate shortening pipelines into your CI/CD, marketing dashboards, or internal scripts using simple JSON HTTP endpoints."
    },
    {
      icon: <RefreshCw className="h-6 w-6 text-pink-600 dark:text-pink-400" />,
      title: "Bulk URL Management",
      description: "Manage, filter, search, and delete shortened links directly from your personal dashboard with simple click controls."
    }
  ];

  return (
    <div className="flex-grow flex flex-col bg-white dark:bg-slate-900 transition-colors duration-300">
      <Header username={username} onLogout={onLogout} onOpenAuth={onOpenAuth} onOpenInfo={onOpenInfo} />
      
      <main className="flex-grow py-16 px-4 max-w-6xl mx-auto w-full">
        {/* Hero header */}
        <div className="text-center mb-16">
          <h1 className="text-4xl font-extrabold text-slate-900 dark:text-white tracking-tight sm:text-5xl mb-4">
            Supercharge your links with ShortUrl
          </h1>
          <p className="max-w-2xl mx-auto text-slate-500 dark:text-slate-400 text-lg">
            Everything you need to shrink URLs, bypass performance bottlenecks, and capture deep analytical marketing insights.
          </p>
        </div>

        {/* Feature Grid */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8 mb-20">
          {featureList.map((f, i) => (
            <div key={i} className="p-6 rounded-xl border border-slate-200 dark:border-slate-800 bg-slate-50/50 dark:bg-slate-800/50 hover:shadow-md transition-all duration-200">
              <div className="bg-white dark:bg-slate-700 w-12 h-12 rounded-lg flex items-center justify-center shadow-sm mb-5">
                {f.icon}
              </div>
              <h3 className="text-lg font-bold text-slate-900 dark:text-white mb-2">{f.title}</h3>
              <p className="text-slate-500 dark:text-slate-400 text-sm leading-relaxed">{f.description}</p>
            </div>
          ))}
        </div>

        {/* Bottom CTA */}
        <div className="bg-slate-900 dark:bg-slate-800 rounded-2xl p-10 text-center relative overflow-hidden">
          <div className="absolute top-0 right-0 w-32 h-32 bg-blue-600 rounded-full filter blur-3xl opacity-20" />
          <h2 className="text-2xl font-bold text-white mb-4">Ready to start shortening?</h2>
          <p className="text-slate-300 text-sm max-w-md mx-auto mb-6">
            Get started for free and upgrade as your marketing scale grows.
          </p>
          <button 
            onClick={() => onOpenAuth('signup')}
            className="bg-blue-600 hover:bg-blue-700 text-white font-semibold text-sm px-6 py-2.5 rounded-lg shadow-sm transition-colors cursor-pointer"
          >
            Create Your Account
          </button>
        </div>
      </main>
    </div>
  );
}
